feat/LM-20-create-test-cases-for-landing-page
ThesisVault/thesis-vault pull request #10
Opened 2024-10-07 06:46 UTC by TJYumul

## **Related Issues/Tasks**

- [LM-20](https://vgonzales5157.atlassian.net/browse/LM-20)

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**
- none

## Description
- create test cases for landing page

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

[x] - I set the PR title based on the following format: feat/LM-20-create-test-cases-for-landing-page

[x] - I set the branch name based on the following format: feat/LM-20-create-test-cases-for-landing-page

[x] - I set KuroXI as the reviewer and assignee of this PR

[x] - I set the correct PR Labels

[x] - All new and existing tests passed

[x] - I did not skip/commented-out/removed any existing tests

[x] - I have performed a self-review of my code

2024-10-07 19:59 UTC, TJYumul commented on package.json
> +    "npm": "^10.9.0",
I have already removed it

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/__test__/landingpage.test.tsx
I already run the pnpm format

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/__test__/landingpage.test.tsx
> +import "@testing-library/jest-dom";
ctrl s didn't work I don't know why I have the extensions already but I manually organize the imports.

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/__test__/landingpage.test.tsx
> +describe("Navbar", () => {
I organize the test files

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/__test__/landingpage.test.tsx
> +describe("SearchBar", () => {
I organize the test files

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/__test__/landingpage.test.tsx
> +describe("Footer", () => {
I organize the test files

2024-10-07 20:05 UTC, TJYumul commented on src/shared/components/common/Navbar.tsx
>  						<AvatarImage src="https://img.freepik.com/free-psd/3d-rendering-avatar_23-2150833554.jpg?w=740&t=st=1727684407~exp=1727685007~hmac=d94e2a5c2e158613a4c66e0b4623ffba571b35d2be28981616569d772951be
I didn't notice the '&'. I added it again. Sorry for the oversight.

2024-10-07 20:05 UTC, TJYumul commented on package.json
> +    "npm": "^10.9.0",
I have already removed it

2024-10-08 15:20 UTC, KuroXI requested changes
can you rename the component and this test

Component: `NavigationBar`
Test: `navigationBar`

after this I think we can merge this PR

2024-11-06 14:05 UTC, KuroXI approved these changes

2024-11-06 14:08 UTC, merged