feat/TV-29-implement-user-role-management-logic
ThesisVault/thesis-vault pull request #33
Opened 2024-11-13 11:22 UTC by Arvicss

## **Related Issues/Tasks**

- Link your jira task here e.g. [LM-X](link)

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**

- none

## Description
- Moved the components folder  from /shared folder to /src folder.
- Implement User domain model, factory, mapper and repository.
- Create test cases for User, Factory, Mapper and Repository.

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

[X] - I set the PR title based on the following format: {task_type}/{task_id}-{task_name} . e.g. feat/LM-X-add-new-functionality (camelCase)

[X] - I set the branch name based on the following format: {branch_type}/{task_id}-{task_name}. e.g feat/LM-X-add-new-functionality

[X] - I set KuroXI as the reviewer and assignee of this PR

[X] - I set the correct PR Labels

[X] - All new and existing tests passed

[X] - I did not skip/commented-out/removed any existing tests

[X] - I have performed a self-review of my code

2024-11-13 12:32 UTC, KuroXI requested changes
Please follow our file structure because it's hard to review when test comes up first before the implementation. Over all good job on your work!

```
- modules
  - user
    - src
    - test
```

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/factory.ts
> +export interface IUserFactoryProps {
I think it's better to call it `IUserFactory`

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/factory.ts
> +
Remove space since those 2 are related to each other

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userRole.ts
> +  private constructor(private readonly _value: Roles) {
Is this best practice?

I think it would be readable if we just stick on how we normally initialize value in class

```typescript
private readonly _value: Roles;

constructor(value: Roles) {
  this._value = value;
}
```

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userRole.ts
> +    const roles = Object.values(Roles);
Is there a better way to handle this? A way that we don't need to use `Object.values()`

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userPermission.ts
> +  private constructor(private readonly _value: number) {
Is this best practice?

I think it would be readable if we just stick on how we normally initialize value in class

```typescript
private readonly _value: number;

constructor(value: number) {
  this._value = value;
}
```

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userPermission.ts
> +    if (permissionBits < 0) {
Please make the minumum value as constant

```ts
private static readonly MINIMUM_PERMISSION_BITS_VALUE = 0;
```

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userName.ts
> +    if (userName.length > 60) {
Please make the maximum length of user name as constant

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userName.ts
> +  private constructor(private readonly _value: string) {
Is this best practice?

I think it would be readable if we just stick on how we normally initialize value in class

```typescript
private readonly _value: string;

constructor(value: string) {
  this._value = value;
}
```

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/user.ts
Remove comments

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/repositories/userRepository.test.ts
> +  const mockUserData = {
It's better to use different data each test. Please apply to other test

Use `faker.js` npm package to get different kinds of data each test

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/repositories/userRepository.test.ts
> +  it("should retrieve a user by Id", async () => {
Duplicate test. I think the other one is better since it checks every properties.

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/repositories/userRepository.test.ts
> +  it("should return permission bits of a user", async () => {
Format this

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/repositories/userRepository.test.ts
> +    expect(user.email).toBe("new.email@neu.edu.ph");
Fetch the user using `userRepository.getUserById()` to check if it actually get updated

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/domain/models/user/classes/userRole.test.ts
> +    expect(result.getValue().value).toBe(Roles.ADMIN);
Self-define it rather than using enum Roles

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/domain/models/user/factory.test.ts
> +  it("should fail if a properties are invalid", () => {
What's the different of this test between the others?

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/domain/models/user/factory.test.ts
> +  it("should fail if UserPermission creation fails", () => {
I think it's better to call it `should fail when permission have negative value`

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/domain/models/user/factory.test.ts
> +  it("should fail if UserRole creation fails", () => {
I think it's better to call it `should fail when role is invalid`

2024-11-13 12:32 UTC, KuroXI commented on src/modules/user/__test__/domain/models/user/factory.test.ts
> +  it("should fail if UserName creation fails", () => {
I think it's better to call it `should fail if name is greater than the maximum value`

2024-11-13 14:27 UTC, Arvicss commented on src/modules/user/src/repositories/userRepository.ts
> +    const userRaw = await db.user.findFirstOrThrow({
I think throwing an error here is better than return `null ` or `undefined`.  We don't need to do manual check on where its used e.g. usecase or service.

2024-11-14 01:30 UTC, KuroXI requested changes

2024-11-14 01:30 UTC, KuroXI commented on package.json
> -    "@types/react": "^18",
Why do we need to remove `@types/react` and `@types/react-dom`?

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userName.ts
> +      return Result.fail("Username is limited to 60 characters long");
Please use the constant variable in the error message

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/src/domain/models/user/classes/userPermission.ts
> +      return Result.fail("Permission value must be greater than 0");
Please use the constant variable in the error message

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/src/repositories/userRepository.ts
> +    const userRaw = await db.user.findFirstOrThrow({
What if there's a scenario that we want to create a user when the `getUserById()` is null?

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/test/domain/models/user/classes/user.test.ts
>    it("should get correct values from getters", () => {
redundant test

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/src/repositories/userRepository.ts
> +  async updateUserName(userId: string, name: UserName): Promise<User> {
are we using this method right now?

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/src/repositories/userRepository.ts
> +  async updateUserPermission(userId: string, permission: UserPermission): Promise<User> {
are we using this method right now?

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/test/domain/models/user/factory.test.ts
>    const userProps = {
Use `src/modules/user/test/repositories/userRepository.test.ts` as reference to create a mock data. Please apply it to other test

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/test/repositories/userRepository.test.ts
Each method in the repository have their own testing file

e.g
```
- test/repositories
  - getUserById.test.ts
  - updateUserName.test.ts

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/test/domain/models/user/classes/userPermission.test.ts
> +  it("should create a UserPermission instance with valid permission bits", () => {
1. How would we know if the permission bits is valid or not?
2. Do we have a checker for the value of permission bits?
3. What will happen if the value has been set to '6' which is not a valid `powers of 2` value?

2024-11-14 01:30 UTC, KuroXI commented on src/modules/user/test/mappers/userMapper.test.ts
> +  const userProps = {
Use `src/modules/user/test/repositories/userRepository.test.ts` as reference to create a mock data. Please apply it to other test

2024-11-14 15:09 UTC, KuroXI requested changes

2024-11-14 15:09 UTC, KuroXI commented on src/modules/user/test/domain/models/user/classes/user.test.ts
> +    permissions: UserPermission.create(faker.number.int({ min: 0, max: 4095, multipleOf: 2 })).getValue(),
use `PermissionBits.ALL` in max

2024-11-14 15:09 UTC, KuroXI commented on src/modules/user/test/domain/models/user/classes/userName.test.ts
> +    expect(result.getErrorMessage()).toBe("Username is limited to 60 characters long");
use `UserName.MAXIMUM_USERNAME_LENGTH` constant value in the error message

2024-11-14 15:09 UTC, KuroXI commented on src/modules/user/test/mappers/userMapper.test.ts
> +      permissions: faker.number.int({ min: 0, max: 4095, multipleOf: 2 }),
use `PermissionBits.ALL` in max

2024-11-14 15:09 UTC, KuroXI commented on src/modules/user/test/repositories/getUserById.test.ts
> +      permissions: faker.number.int({ min: 0, max: 4095, multipleOf: 2 }),
use `PermissionBits.ALL` in max

2024-11-14 18:04 UTC, KuroXI approved these changes

2024-11-14 18:04 UTC, merged