feat/TV-34-implement-update-user-permission-usecase
ThesisVault/thesis-vault pull request #38
Opened 2024-11-17 19:17 UTC by Arvicss

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**
- Do I need to test `userRouter`? If yes, how?

## Description
- implement updateUserPermissionUseCase
- implement updateUserPermissionController
- define application errors
- create test cases

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

- [x] I set the PR title based on the following format: [{task_type}] {task_id}: {task_name} . e.g. [feat] TV-X: add-new-functionality (camelCase)

- [x] I set the branch name based on the following format: {branch_type}/{task_id}-{task_name}. e.g feat/LM-X-add-new-functionality

- [x] I set KuroXI as the reviewer of this PR

- [x] I set myself as an assignees of this PR

- [x] I set the correct labels of this PR

- [x] All new and existing tests passed

- [x] I did not skip/commented-out/removed any existing tests

- [x] I have performed a self-review of my code

2024-11-18 01:45 UTC, KuroXI requested changes
Please also add a test for the endpoint you created.
```
- src
- tests
  - api
    - user
      - updateUserPermission.test.ts
```

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/domain/models/user/classes/user.test.ts
> +import { createUserDomainObject } from "@/modules/user/tests/utils/createUserDomainObject";
Please organize your imports. [Optimize Imports in WebStorm](https://blog.jetbrains.com/webstorm/2018/05/optimize-imports-in-webstorm/)

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/domain/models/user/service/userPermissionService.test.ts
> +  afterEach(async () => {
I think `deleteMany` is not necessary here

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/updateUserPermissionController.test.ts
> +    controller = new UpdateUserPermissionController(userPermissionServiceMock, updateUserPermissionUseCaseMock);
why initialize the service and useCase here when it's already been initialized inside controller?

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/repositories/updateUser.test.ts
> +  afterEach(async () => {
I think deleteMany is not necessary here

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/repositories/updateUsers.test.ts
> +  afterEach(async () => {
I think deleteMany is not necessary here

2024-11-18 01:45 UTC, KuroXI commented on src/modules/user/tests/useCases/updateUserPermissionUseCase.test.ts
> +		updateUserPermissionUseCase = new UpdateUserPermissionUseCase(userRepositoryMock);
Why mock the repository?

2024-11-18 02:05 UTC, KuroXI commented
@Arvicss To test your userRouter, we can import `auth` and `trpc` in our test cases since they're on the shared folder.

- `src/shared/infrastructure/authentication/index.ts`
- `src/shared/infrastructure/trpc/api/server.ts`.

Then we can call the `getServerAuthSession()` from auth and `updateUserPermission` from userRouter.

We also need to create a session in `beforeAll(() => {})` so that we can use the protectedProcedure you created.

Add a test also for the unauthorized request and user that does not have the required permission.

```ts
describe("userRouter updateUserPermission endpoint", () => {
  beforeAll(() => {
    // authenticate user
  })

  describe("User is authorized", () => {
    it("should return an error if user does not have MANAGE_USER permission")
    // ...
  })
  
  describe("User is un-authorized", () => {
    it("should return an error if user is not authenticated")
    // ...
  })
})
```

This is solely an idea, feel free to improve this.

2024-11-19 01:54 UTC, KuroXI requested changes
Please rebase into master

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/src/repositories/userRepository.ts
> +	async updateUser(data: IUser): Promise<IUser | null> {
Please add this to `IUserRepository` and always make sure private method are in the bottom

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/src/domain/models/user/service/userPermissionService.ts
You can delete this file and use `src/modules/user/src/domain/services/userPermissionService.ts`

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/src/shared/permissions.ts
> +export type PermissionKeys =  keyof typeof Permissions;
Fix your formatter

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/tests/domain/models/user/service/userPermissionService.test.ts
You can now delete this file and please rebase to the master

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/tests/utils/createUserDomainObject.ts
You can now remove this file

2024-11-19 01:54 UTC, KuroXI commented on src/modules/user/src/useCases/updateUserPermissionUseCase.ts
User permission now have 2 properties which is `allowPermissions` and `denyPermissions`.

Please update your implementation and sync the sequence diagram to your implementation.

2024-11-19 14:27 UTC, Arvicss commented
I'm having issues getting the tRPC route test to run. I've tried changing test configuration multiple times, but  still encountering the same error.


FAIL   node-tests  src/modules/user/tests/api/user/updatePermission.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    F:\Programming Projects\Web\thesis-vault\node_modules\.pnpm\superjson@2.2.1\node_modules\superjson\dist\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { ClassRegistry } from './class-registry.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { TRPCError, initTRPC } from "@trpc/server";
    > 2 | import superjson from "superjson";
        | ^
      3 | import { ZodError } from "zod";
      4 | import { getServerAuthSession } from "../authentication";
      5 | import { db } from "../database";

      at Runtime.createScriptFromCode (node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/shared/infrastructure/trpc/index.ts:2:1)
      at Object.<anonymous> (src/shared/infrastructure/trpc/routes.ts:1:1)
      at Object.<anonymous> (src/modules/user/tests/api/user/updatePermission.test.ts:3:1)

2024-11-19 16:06 UTC, KuroXI requested changes

2024-11-19 16:06 UTC, KuroXI commented on src/modules/user/tests/useCases/updateUserPermissionUseCase.test.ts
> +	it("should successfully update user permission and return userId", async () => {
Why are we not checking if the `denyPermission` got updated? Please double check your implementation

2024-11-19 17:18 UTC, Arvicss commented on src/modules/user/src/useCases/updateUserPermissionUseCase.ts
> +export class UpdateUserPermissionUseCase {
![image](https://github.com/user-attachments/assets/40c7e481-b1c6-47eb-af11-94a7d2357ebc)

2024-11-19 17:52 UTC, KuroXI requested changes

2024-11-19 17:52 UTC, KuroXI commented on src/modules/user/tests/repositories/user/updateUser.test.ts
> +  let userRepository: UserRepository;
use `IUserRepository`

2024-11-19 17:52 UTC, KuroXI commented on src/modules/user/tests/repositories/user/updateUsers.test.ts
> +	let userRepository: UserRepository;
use `IUserRepository`

2024-11-19 17:52 UTC, KuroXI commented on src/modules/user/tests/useCases/updateUserPermissionUseCase.test.ts
> +	const updateUserPermissionUseCase = new UpdateUserPermissionUseCase();
Be consistent on how you initialize a class in test

Use reference: `src/modules/user/tests/repositories/user/updateUsers.test.ts`

2024-11-19 17:52 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/updateUserPermissionController.test.ts
> +  const updateUserPermissionController = new UpdateUserPermissionController();
Be consistent on how you initialize a class in test

Use reference: `src/modules/user/tests/repositories/user/updateUsers.test.ts`

2024-11-19 18:41 UTC, KuroXI requested changes

2024-11-19 18:41 UTC, KuroXI commented on src/modules/user/src/infrastructure/http/controllers/updateUserPermissionController.ts
> +  private userPermissionService: UserPermissionService;
Use the interface of the class not the class itself.

e.g `IUserPermissionService`

2024-11-19 18:52 UTC, KuroXI approved these changes

2024-11-19 18:52 UTC, merged