feat/TV-35-implement-update-user-role-id-useCase
ThesisVault/thesis-vault pull request #42
Opened 2024-11-20 11:37 UTC by TJYumul

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**
- Respond with "none" if nothing applies

## Description
- implement updateUserRoleIdUseCase
- implement updateUserRoleIdController
- create a test cases

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

- [x] I set the PR title based on the following format: [{task_type}] {task_id}: {task_name} . e.g. [feat] TV-X: add-new-functionality (camelCase)

- [x] I set the branch name based on the following format: {branch_type}/{task_id}-{task_name}. e.g feat/LM-X-add-new-functionality

- [x] I set KuroXI as the reviewer of this PR

- [x] I set myself as an assignees of this PR

- [x] I set the correct labels of this PR

- [x] All new and existing tests passed

- [x] I did not skip/commented-out/removed any existing tests

- [x] I have performed a self-review of my code

2024-11-20 14:25 UTC, KuroXI requested changes
When you're doing a testing place the working test in the first and the error test in the last

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
> +		updateUserRoleIdController = new UpdateUserRoleIdController(
I think we don't need to initialize it since it's already been initialize in side the controller's constructor

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
> +	it("should throw an UnauthorizedError when the editor does not have the required permissions", async () => {
I think this should be `should throw an UnauthorizedError when the user who requested does not have the required permissions`

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
Use `src/modules/user/tests/infrastructure/http/controllers/updateUserPermissionController.test.ts` as your reference

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/repositories/user/updateUser.test.ts
>    it("should update user properties", async () => {
Please assert if the roleId gets updated

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/repositories/user/updateUsers.test.ts
Fix your formatter. Use `2 tab`

2024-11-20 14:25 UTC, KuroXI commented on src/modules/user/tests/useCases/updateUserRoleIdUseCase.test.ts
> +	it("should successfully update the user role and return the updated user ID", async () => {
Maybe we seed another user for the `requestedById`

2024-11-21 00:14 UTC, TJYumul commented on src/modules/user/src/domain/models/user/classes/user.ts
> +	updateRoleId(roleId: string | null): void;
Already fix following the line 20

2024-11-21 00:15 UTC, TJYumul commented on src/modules/user/src/dtos/updateUserRoleIdDTO.ts
Already deleted updateUserRoleIdDTO.ts and paste it in userDTO.ts

2024-11-21 00:17 UTC, TJYumul commented on src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
> +	public async execute(request: UpdateUserRoleIdDTO): Promise<string> {
I applied the single level of abstraction

2024-11-21 00:18 UTC, TJYumul commented on src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
> +		updateUserRoleIdController = new UpdateUserRoleIdController(
Already removed the permissionService and roleIdUseCase

2024-11-21 00:19 UTC, TJYumul commented on src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
> +	it("should throw an UnauthorizedError when the editor does not have the required permissions", async () => {
Done

2024-11-21 00:20 UTC, TJYumul commented on src/modules/user/tests/repositories/user/updateUser.test.ts
>    it("should update user properties", async () => {
Done

2024-11-21 00:20 UTC, TJYumul commented on src/modules/user/tests/useCases/updateUserRoleIdUseCase.test.ts
> +	it("should successfully update the user role and return the updated user ID", async () => {
Done

2024-11-21 04:37 UTC, KuroXI requested changes
I think it's better to add `_` as prefix when the variable or method is private.

For example:
- `private _userRepository: IUserRepository;`
- `private async _getRoleById(roleId: string)`

2024-11-21 15:25 UTC, KuroXI requested changes

2024-11-21 15:25 UTC, KuroXI commented on src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
> +		const role = await this.getRoleById(request.roleId);
I think we don't need to set the variable for this one since we just want to check if that roleId exist.

2024-11-21 15:25 UTC, KuroXI commented on src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
> +	public async getRoleById(roleId: string) {
This should not return a value since we're just checking if the roleId exist.

I think it's better to call it `ensureRoleIdExist`

2024-11-22 01:38 UTC, KuroXI requested changes

2024-11-22 01:38 UTC, KuroXI commented on src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
> +	private async _ensureRoleIdExists(roleId: string) {
I think we can do this like

```ts
private async _ensureRoleIdExists(roleId: string | null): Promise<void> {
	if (roleId === null) return;
	
	const role = await this._roleRepository.getRoleById(roleId);
	if (role === null) {
		throw new NotFoundError(`Role ${roleId} not found`);
	}
}
```

So that we don't need to check it in the execute.
```ts
public async execute(request: UpdateUserRoleIdDTO): Promise<string> {
	await this._ensureRoleIdExists(request.roleId);

	const user = await this._getUserById(request.userId);
	user.updateRoleId(request.roleId);

	const updatedUser = await this._updateUser(user);

	return updatedUser.id;
}
```

2024-11-22 01:38 UTC, KuroXI commented on src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
> +	private async _updateUser(user: IUser) {
Maybe we can also update the user's role inside this method? What do you think?

So that our execute will only have abstraction level 1
```ts
await this._ensureRoleIdExists(request.roleId);

const user = await this._getUserById(request.userId);
const updatedUser = await this._updateUserRoleId(user, request.roleId);

return updatedUser.id;
```

2024-11-22 01:38 UTC, KuroXI commented on src/modules/user/tests/useCases/updateUserRoleIdUseCase.test.ts
> +	it("should not throw error if roleId is null", async () => {
1. Fix format
2. I think this should be called "should update the user roleId to null"
3. Assert the things you update which is the roleId.

2024-11-22 04:38 UTC, KuroXI approved these changes

2024-11-22 04:38 UTC, merged