feat/TV-55-implement-deleteUserUseCase
ThesisVault/thesis-vault pull request #63
Opened 2024-12-04 12:17 UTC by Arvicss

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**
- none

## Description
- deleteUserUseCase
- deleteUserController
- deleteUserRoute
- test cases

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

- [X] I set the PR title based on the following format: [{task_type}] {task_id}: {task_name} . e.g. [feat] TV-X: add-new-functionality (camelCase)

- [X] I set the branch name based on the following format: {branch_type}/{task_id}-{task_name}. e.g feat/LM-X-add-new-functionality

- [X] I set KuroXI as the reviewer of this PR

- [X] I set myself as an assignees of this PR

- [X] I set the correct labels of this PR

- [X] All new and existing tests passed

- [X] I did not skip/commented-out/removed any existing tests

- [X] I have performed a self-review of my code

2024-12-04 13:49 UTC, KuroXI requested changes

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/src/domain/services/userAuditLogService.ts
> +
Remove this space as they are related to each other

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/src/infrastructure/http/controllers/user/deleteUserController.ts
> +  private userPermissionService: IUserPermissionService;
Please add `_` when it's a private

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/tests/domain/services/userAuditLogService.test.ts
> +		expect(userAuditLogs[0].type._value).toBe(params.type);
We can use `typeValue`. I forgot to add it when I refactor the `userAuditLog`
![image](https://github.com/user-attachments/assets/c72cf92a-94e3-46b7-a951-39c55643dc0e)
![image](https://github.com/user-attachments/assets/5cb194ec-494f-431a-81c7-3bdf9530e5c2)

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/src/domain/services/userAuditLogService.ts
> +		await this._userAuditLogRepository.createUserAuditLog(auditLogOrError.getValue());
Do you think we can do it like [this](https://github.com/prisma/prisma/issues/8131#issuecomment-997667070) when we are creating the `userAuditLogs`, so that we can get the returning records of that creation?

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/tests/infrastructure/http/controllers/user/deleteUserController.ts
Did you test this? I don't think it's possible to test typescript file

2024-12-04 13:49 UTC, KuroXI commented on src/modules/user/tests/useCases/deleteUserUseCase.test.ts
> +		expect(deletedUser?.id).toBe(seededUser.id);
Use `!` instead of `?`

2024-12-04 13:49 UTC, KuroXI commented on package.json
>  		"test": "jest --config .jestrc.json --runInBand",
Please add `--testTimeout=30000`

2024-12-04 16:14 UTC, Arvicss commented on package.json
>  		"test": "jest --config .jestrc.json --runInBand",
I added it to the main config

2024-12-05 03:45 UTC, KuroXI requested changes

2024-12-05 03:45 UTC, KuroXI commented on src/modules/user/src/repositories/userAuditLogRepository.ts
> +	createUserAuditLog(data: IUserAuditLog): Promise<IUserAuditLog | null>;
Sorry can you change the `data` into `auditLog`

2024-12-05 03:45 UTC, KuroXI commented on src/modules/user/src/domain/services/userAuditLogService.ts
> +	createAndSaveUserAuditLog(params: CreateAndSaveUserAuditLogDTO ): Promise<void>;
Remove space in the parameter

2024-12-05 03:45 UTC, KuroXI commented on src/modules/user/src/domain/services/userAuditLogService.ts
> +	public async createAndSaveUserAuditLog(params: CreateAndSaveUserAuditLogDTO ): Promise<void> {
Remove space in the parameter

2024-12-05 03:45 UTC, KuroXI commented on src/modules/user/tests/domain/models/user/classes/user.test.ts
> +			expect(user.deletedAt).toBe(null);
expect().toBeNull()

2024-12-05 03:45 UTC, KuroXI commented on src/modules/user/tests/useCases/deleteUserUseCase.test.ts
> +	it("should successfully soft delete a user", async () => {
Can we also assert the auditLog if it actually got created?

2024-12-05 05:42 UTC, KuroXI approved these changes

2024-12-05 05:43 UTC, merged