feat/TV-58-implement-createRoleUseCase
ThesisVault/thesis-vault pull request #81
Opened 2024-12-10 05:16 UTC by frenchMontajes

## PR Question
**Do you have specific questions or issues you would like to address with the reviewer?**
- None

## Description
- created createRoleUseCase

## PR/Code Author Checklist
**Note:** please write "x" within the brackets if item applies e.g. [x]

- [x] I set the PR title based on the following format: [{task_type}] {task_id}: {task_name} . e.g. [feat] TV-X: add-new-functionality (camelCase)

- [x] I set the branch name based on the following format: {branch_type}/{task_id}-{task_name}. e.g feat/LM-X-add-new-functionality

- [x] I set KuroXI as the reviewer of this PR

- [x] I set myself as an assignees of this PR

- [x] I set the correct labels of this PR

- [x] All new and existing tests passed

- [x] I did not skip/commented-out/removed any existing tests

- [x] I have performed a self-review of my code

2024-12-10 13:26 UTC, Arvicss requested changes
Rebase Branch

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/src/useCases/role/createRoleUseCase.ts
> +			deletedAt: null,
remove createdAt, updatedAt, isDeleted, deletedAt

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/src/useCases/role/createRoleUseCase.ts
> +
remove empty line

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/src/useCases/role/createRoleUseCase.ts
> +		const role = await this._roleRepository.createRole(roleOrFailure.getValue());
add empty line before this variable

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/src/useCases/role/createRoleUseCase.ts
> +
remove empty line

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/tests/infrastructure/http/routes/role/createRole.test.ts
> +	describe("User is authenticated", () => {
fix spacing add empty line in between

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/tests/infrastructure/http/routes/role/createRole.test.ts
> +			expect(createRole!.color).toBe(request.color);
Remove this assertion. Out of test scope.

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/tests/infrastructure/http/routes/role/createRole.test.ts
> +			const roleId = await caller.createRole(request);
assert that roleId is not null

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/src/useCases/role/createRoleUseCase.ts
> +	public async execute(request: CreateRoleDTO) {
add return type

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/tests/useCases/role/createRoleUseCase.test.ts
> +	let roleRepository: RoleRepository;
use `IRoleRepository`

2024-12-10 13:26 UTC, Arvicss commented on src/modules/user/tests/useCases/role/createRoleUseCase.test.ts
> +
assert the following:

`isDeleted`
`deletedAt`
`updatedAt`

2024-12-11 09:26 UTC, KuroXI approved these changes

2024-12-11 09:28 UTC, merged